# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Alarms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Events_pb2 as Events__pb2
import Model_pb2 as Model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Alarms.proto',
  package='org.totalgrid.reef.client.service.proto.Alarms',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.protoB\006Alarms',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x41larms.proto\x12.org.totalgrid.reef.client.service.proto.Alarms\x1a\x0c\x45vents.proto\x1a\x0bModel.proto\"\xbb\x02\n\x05\x41larm\x12\x41\n\x02id\x18\x01 \x01(\x0b\x32\x35.org.totalgrid.reef.client.service.proto.Model.ReefID\x12J\n\x05state\x18\x02 \x01(\x0e\x32;.org.totalgrid.reef.client.service.proto.Alarms.Alarm.State\x12\x44\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x35.org.totalgrid.reef.client.service.proto.Events.Event\x12\x10\n\x08rendered\x18\x04 \x01(\t\"K\n\x05State\x12\x11\n\rUNACK_AUDIBLE\x10\x01\x12\x10\n\x0cUNACK_SILENT\x10\x02\x12\x10\n\x0c\x41\x43KNOWLEDGED\x10\x03\x12\x0b\n\x07REMOVED\x10\x04\"\xab\x01\n\x0b\x41larmSelect\x12J\n\x05state\x18\x01 \x03(\x0e\x32;.org.totalgrid.reef.client.service.proto.Alarms.Alarm.State\x12P\n\x0b\x65ventSelect\x18\x02 \x01(\x0b\x32;.org.totalgrid.reef.client.service.proto.Events.EventSelect\"\x9f\x01\n\tAlarmList\x12K\n\x06select\x18\x01 \x01(\x0b\x32;.org.totalgrid.reef.client.service.proto.Alarms.AlarmSelect\x12\x45\n\x06\x61larms\x18\x02 \x03(\x0b\x32\x35.org.totalgrid.reef.client.service.proto.Alarms.Alarm\"\xb5\x02\n\x0b\x45ventConfig\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\r\x12\\\n\x0b\x64\x65signation\x18\x03 \x01(\x0e\x32G.org.totalgrid.reef.client.service.proto.Alarms.EventConfig.Designation\x12P\n\x0b\x61larm_state\x18\x04 \x01(\x0e\x32;.org.totalgrid.reef.client.service.proto.Alarms.Alarm.State\x12\x10\n\x08resource\x18\x05 \x01(\t\x12\x10\n\x08\x62uilt_in\x18\x06 \x01(\x08\",\n\x0b\x44\x65signation\x12\t\n\x05\x41LARM\x10\x01\x12\t\n\x05\x45VENT\x10\x02\x12\x07\n\x03LOG\x10\x03\x42\x31\n\'org.totalgrid.reef.client.service.protoB\x06\x41larms'
  ,
  dependencies=[Events__pb2.DESCRIPTOR,Model__pb2.DESCRIPTOR,])



_ALARM_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNACK_AUDIBLE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNACK_SILENT', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACKNOWLEDGED', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=407,
)
_sym_db.RegisterEnumDescriptor(_ALARM_STATE)

_EVENTCONFIG_DESIGNATION = _descriptor.EnumDescriptor(
  name='Designation',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.Designation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALARM', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOG', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1011,
  serialized_end=1055,
)
_sym_db.RegisterEnumDescriptor(_EVENTCONFIG_DESIGNATION)


_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event', full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rendered', full_name='org.totalgrid.reef.client.service.proto.Alarms.Alarm.rendered', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ALARM_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=407,
)


_ALARMSELECT = _descriptor.Descriptor(
  name='AlarmSelect',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmSelect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmSelect.state', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventSelect', full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmSelect.eventSelect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=581,
)


_ALARMLIST = _descriptor.Descriptor(
  name='AlarmList',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='select', full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmList.select', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alarms', full_name='org.totalgrid.reef.client.service.proto.Alarms.AlarmList.alarms', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=743,
)


_EVENTCONFIG = _descriptor.Descriptor(
  name='EventConfig',
  full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_type', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.event_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.severity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='designation', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.designation', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alarm_state', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.alarm_state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.resource', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='built_in', full_name='org.totalgrid.reef.client.service.proto.Alarms.EventConfig.built_in', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTCONFIG_DESIGNATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=1055,
)

_ALARM.fields_by_name['id'].message_type = Model__pb2._REEFID
_ALARM.fields_by_name['state'].enum_type = _ALARM_STATE
_ALARM.fields_by_name['event'].message_type = Events__pb2._EVENT
_ALARM_STATE.containing_type = _ALARM
_ALARMSELECT.fields_by_name['state'].enum_type = _ALARM_STATE
_ALARMSELECT.fields_by_name['eventSelect'].message_type = Events__pb2._EVENTSELECT
_ALARMLIST.fields_by_name['select'].message_type = _ALARMSELECT
_ALARMLIST.fields_by_name['alarms'].message_type = _ALARM
_EVENTCONFIG.fields_by_name['designation'].enum_type = _EVENTCONFIG_DESIGNATION
_EVENTCONFIG.fields_by_name['alarm_state'].enum_type = _ALARM_STATE
_EVENTCONFIG_DESIGNATION.containing_type = _EVENTCONFIG
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
DESCRIPTOR.message_types_by_name['AlarmSelect'] = _ALARMSELECT
DESCRIPTOR.message_types_by_name['AlarmList'] = _ALARMLIST
DESCRIPTOR.message_types_by_name['EventConfig'] = _EVENTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), {
  'DESCRIPTOR' : _ALARM,
  '__module__' : 'Alarms_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Alarms.Alarm)
  })
_sym_db.RegisterMessage(Alarm)

AlarmSelect = _reflection.GeneratedProtocolMessageType('AlarmSelect', (_message.Message,), {
  'DESCRIPTOR' : _ALARMSELECT,
  '__module__' : 'Alarms_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Alarms.AlarmSelect)
  })
_sym_db.RegisterMessage(AlarmSelect)

AlarmList = _reflection.GeneratedProtocolMessageType('AlarmList', (_message.Message,), {
  'DESCRIPTOR' : _ALARMLIST,
  '__module__' : 'Alarms_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Alarms.AlarmList)
  })
_sym_db.RegisterMessage(AlarmList)

EventConfig = _reflection.GeneratedProtocolMessageType('EventConfig', (_message.Message,), {
  'DESCRIPTOR' : _EVENTCONFIG,
  '__module__' : 'Alarms_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Alarms.EventConfig)
  })
_sym_db.RegisterMessage(EventConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
