# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApplicationManagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Model_pb2 as Model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ApplicationManagement.proto',
  package='org.totalgrid.reef.client.service.proto.Application',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.protoB\013Application',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x41pplicationManagement.proto\x12\x33org.totalgrid.reef.client.service.proto.Application\x1a\x0bModel.proto\"O\n\x0fHeartbeatConfig\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x11\n\tperiod_ms\x18\x03 \x01(\r\x12\x15\n\rinstance_name\x18\x05 \x01(\t\"\xf6\x02\n\x11\x41pplicationConfig\x12\x45\n\x04uuid\x18\x01 \x01(\x0b\x32\x37.org.totalgrid.reef.client.service.proto.Model.ReefUUID\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x15\n\rinstance_name\x18\x03 \x01(\t\x12\x12\n\nprocess_id\x18\t \x01(\t\x12\x0f\n\x07version\x18\r \x01(\t\x12\x0f\n\x07network\x18\x04 \x01(\t\x12\x10\n\x08networks\x18\x0c \x03(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61pabilites\x18\x06 \x03(\t\x12[\n\rheartbeat_cfg\x18\x07 \x01(\x0b\x32\x44.org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig\x12\x0e\n\x06online\x18\n \x01(\x08\x12\x14\n\x0ctimes_out_at\x18\x0b \x01(\x04\x42\x36\n\'org.totalgrid.reef.client.service.protoB\x0b\x41pplication'
  ,
  dependencies=[Model__pb2.DESCRIPTOR,])




_HEARTBEATCONFIG = _descriptor.Descriptor(
  name='HeartbeatConfig',
  full_name='org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_id', full_name='org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig.process_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period_ms', full_name='org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig.period_ms', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig.instance_name', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=176,
)


_APPLICATIONCONFIG = _descriptor.Descriptor(
  name='ApplicationConfig',
  full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.instance_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.process_id', index=3,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.version', index=4,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.network', index=5,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='networks', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.networks', index=6,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.location', index=7,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capabilites', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.capabilites', index=8,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heartbeat_cfg', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.heartbeat_cfg', index=9,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='online', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.online', index=10,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times_out_at', full_name='org.totalgrid.reef.client.service.proto.Application.ApplicationConfig.times_out_at', index=11,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=553,
)

_APPLICATIONCONFIG.fields_by_name['uuid'].message_type = Model__pb2._REEFUUID
_APPLICATIONCONFIG.fields_by_name['heartbeat_cfg'].message_type = _HEARTBEATCONFIG
DESCRIPTOR.message_types_by_name['HeartbeatConfig'] = _HEARTBEATCONFIG
DESCRIPTOR.message_types_by_name['ApplicationConfig'] = _APPLICATIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatConfig = _reflection.GeneratedProtocolMessageType('HeartbeatConfig', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATCONFIG,
  '__module__' : 'ApplicationManagement_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Application.HeartbeatConfig)
  })
_sym_db.RegisterMessage(HeartbeatConfig)

ApplicationConfig = _reflection.GeneratedProtocolMessageType('ApplicationConfig', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONCONFIG,
  '__module__' : 'ApplicationManagement_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Application.ApplicationConfig)
  })
_sym_db.RegisterMessage(ApplicationConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
