# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeasurementMapping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MeasurementMapping.proto',
  package='org.totalgrid.reef.client.service.proto.Mapping',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.protoB\007Mapping',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18MeasurementMapping.proto\x12/org.totalgrid.reef.client.service.proto.Mapping\"\x94\x01\n\x07MeasMap\x12G\n\x04type\x18\x01 \x02(\x0e\x32\x39.org.totalgrid.reef.client.service.proto.Mapping.DataType\x12\r\n\x05index\x18\x02 \x02(\r\x12\x12\n\npoint_name\x18\x03 \x02(\t\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x0f\n\x07scaling\x18\x05 \x01(\x01\"\xcd\x01\n\nCommandMap\x12J\n\x04type\x18\x01 \x02(\x0e\x32<.org.totalgrid.reef.client.service.proto.Mapping.CommandType\x12\r\n\x05index\x18\x02 \x02(\r\x12\x14\n\x0c\x63ommand_name\x18\x03 \x02(\t\x12\x14\n\x07on_time\x18\x04 \x01(\r:\x03\x31\x30\x30\x12\x15\n\x08off_time\x18\x05 \x01(\r:\x03\x31\x30\x30\x12\x10\n\x05\x63ount\x18\x06 \x01(\r:\x01\x31\x12\x0f\n\x07scaling\x18\x07 \x01(\x01\"\xbd\x01\n\x0cIndexMapping\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12I\n\x07measmap\x18\x03 \x03(\x0b\x32\x38.org.totalgrid.reef.client.service.proto.Mapping.MeasMap\x12O\n\ncommandmap\x18\x04 \x03(\x0b\x32;.org.totalgrid.reef.client.service.proto.Mapping.CommandMap*X\n\x08\x44\x61taType\x12\n\n\x06\x41NALOG\x10\x01\x12\n\n\x06\x42INARY\x10\x02\x12\x0b\n\x07\x43OUNTER\x10\x03\x12\x12\n\x0e\x43ONTROL_STATUS\x10\x04\x12\x13\n\x0fSETPOINT_STATUS\x10\x05*d\n\x0b\x43ommandType\x12\t\n\x05PULSE\x10\x01\x12\x0c\n\x08LATCH_ON\x10\x02\x12\r\n\tLATCH_OFF\x10\x03\x12\x0f\n\x0bPULSE_CLOSE\x10\x04\x12\x0e\n\nPULSE_TRIP\x10\x05\x12\x0c\n\x08SETPOINT\x10\x06\x42\x32\n\'org.totalgrid.reef.client.service.protoB\x07Mapping'
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='org.totalgrid.reef.client.service.proto.Mapping.DataType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANALOG', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BINARY', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNTER', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTROL_STATUS', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SETPOINT_STATUS', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=628,
  serialized_end=716,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PULSE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LATCH_ON', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LATCH_OFF', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PULSE_CLOSE', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PULSE_TRIP', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SETPOINT', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=718,
  serialized_end=818,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
ANALOG = 1
BINARY = 2
COUNTER = 3
CONTROL_STATUS = 4
SETPOINT_STATUS = 5
PULSE = 1
LATCH_ON = 2
LATCH_OFF = 3
PULSE_CLOSE = 4
PULSE_TRIP = 5
SETPOINT = 6



_MEASMAP = _descriptor.Descriptor(
  name='MeasMap',
  full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap.index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point_name', full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap.point_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap.unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scaling', full_name='org.totalgrid.reef.client.service.proto.Mapping.MeasMap.scaling', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=226,
)


_COMMANDMAP = _descriptor.Descriptor(
  name='CommandMap',
  full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command_name', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.command_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='on_time', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.on_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='off_time', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.off_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scaling', full_name='org.totalgrid.reef.client.service.proto.Mapping.CommandMap.scaling', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=434,
)


_INDEXMAPPING = _descriptor.Descriptor(
  name='IndexMapping',
  full_name='org.totalgrid.reef.client.service.proto.Mapping.IndexMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='org.totalgrid.reef.client.service.proto.Mapping.IndexMapping.device_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measmap', full_name='org.totalgrid.reef.client.service.proto.Mapping.IndexMapping.measmap', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commandmap', full_name='org.totalgrid.reef.client.service.proto.Mapping.IndexMapping.commandmap', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=626,
)

_MEASMAP.fields_by_name['type'].enum_type = _DATATYPE
_COMMANDMAP.fields_by_name['type'].enum_type = _COMMANDTYPE
_INDEXMAPPING.fields_by_name['measmap'].message_type = _MEASMAP
_INDEXMAPPING.fields_by_name['commandmap'].message_type = _COMMANDMAP
DESCRIPTOR.message_types_by_name['MeasMap'] = _MEASMAP
DESCRIPTOR.message_types_by_name['CommandMap'] = _COMMANDMAP
DESCRIPTOR.message_types_by_name['IndexMapping'] = _INDEXMAPPING
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeasMap = _reflection.GeneratedProtocolMessageType('MeasMap', (_message.Message,), {
  'DESCRIPTOR' : _MEASMAP,
  '__module__' : 'MeasurementMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Mapping.MeasMap)
  })
_sym_db.RegisterMessage(MeasMap)

CommandMap = _reflection.GeneratedProtocolMessageType('CommandMap', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMAP,
  '__module__' : 'MeasurementMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Mapping.CommandMap)
  })
_sym_db.RegisterMessage(CommandMap)

IndexMapping = _reflection.GeneratedProtocolMessageType('IndexMapping', (_message.Message,), {
  'DESCRIPTOR' : _INDEXMAPPING,
  '__module__' : 'MeasurementMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Mapping.IndexMapping)
  })
_sym_db.RegisterMessage(IndexMapping)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
