# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Model_pb2 as Model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProcessStatus.proto',
  package='org.totalgrid.reef.client.service.proto.ProcessStatus',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13ProcessStatus.proto\x12\x35org.totalgrid.reef.client.service.proto.ProcessStatus\x1a\x0bModel.proto\"\\\n\x0eStatusSnapshot\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x15\n\rinstance_name\x18\x02 \x01(\t\x12\x0e\n\x06online\x18\x03 \x01(\x08\x12\x0f\n\x04time\x18\x04 \x01(\x04:\x01\x30\x42)\n\'org.totalgrid.reef.client.service.proto'
  ,
  dependencies=[Model__pb2.DESCRIPTOR,])




_STATUSSNAPSHOT = _descriptor.Descriptor(
  name='StatusSnapshot',
  full_name='org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_id', full_name='org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot.process_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_name', full_name='org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot.instance_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='online', full_name='org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot.online', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot.time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['StatusSnapshot'] = _STATUSSNAPSHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusSnapshot = _reflection.GeneratedProtocolMessageType('StatusSnapshot', (_message.Message,), {
  'DESCRIPTOR' : _STATUSSNAPSHOT,
  '__module__' : 'ProcessStatus_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.ProcessStatus.StatusSnapshot)
  })
_sym_db.RegisterMessage(StatusSnapshot)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
