# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimulatorMapping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Measurements_pb2 as Measurements__pb2
import Commands_pb2 as Commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimulatorMapping.proto',
  package='org.totalgrid.reef.client.service.proto.Simulator',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.protoB\nSimMapping',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16SimulatorMapping.proto\x12\x31org.totalgrid.reef.client.service.proto.Simulator\x1a\x12Measurements.proto\x1a\x0e\x43ommands.proto\"\xd0\x01\n\x07MeasSim\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04unit\x18\x02 \x02(\t\x12T\n\x04type\x18\x03 \x02(\x0e\x32\x46.org.totalgrid.reef.client.service.proto.Measurements.Measurement.Type\x12\x0f\n\x07initial\x18\x04 \x01(\x01\x12\x0b\n\x03min\x18\x05 \x01(\x01\x12\x0b\n\x03max\x18\x06 \x01(\x01\x12\x11\n\tmax_delta\x18\x07 \x01(\x01\x12\x15\n\rchange_chance\x18\x08 \x01(\x01\"t\n\nCommandSim\x12\x0c\n\x04name\x18\x01 \x02(\t\x12X\n\x0fresponse_status\x18\x02 \x02(\x0e\x32?.org.totalgrid.reef.client.service.proto.Commands.CommandStatus\"\xc4\x01\n\x10SimulatorMapping\x12\r\n\x05\x64\x65lay\x18\x01 \x02(\r\x12P\n\x0cmeasurements\x18\x03 \x03(\x0b\x32:.org.totalgrid.reef.client.service.proto.Simulator.MeasSim\x12O\n\x08\x63ommands\x18\x04 \x03(\x0b\x32=.org.totalgrid.reef.client.service.proto.Simulator.CommandSimB5\n\'org.totalgrid.reef.client.service.protoB\nSimMapping'
  ,
  dependencies=[Measurements__pb2.DESCRIPTOR,Commands__pb2.DESCRIPTOR,])




_MEASSIM = _descriptor.Descriptor(
  name='MeasSim',
  full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.unit', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.initial', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.min', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.max', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_delta', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.max_delta', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change_chance', full_name='org.totalgrid.reef.client.service.proto.Simulator.MeasSim.change_chance', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=322,
)


_COMMANDSIM = _descriptor.Descriptor(
  name='CommandSim',
  full_name='org.totalgrid.reef.client.service.proto.Simulator.CommandSim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.totalgrid.reef.client.service.proto.Simulator.CommandSim.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_status', full_name='org.totalgrid.reef.client.service.proto.Simulator.CommandSim.response_status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=440,
)


_SIMULATORMAPPING = _descriptor.Descriptor(
  name='SimulatorMapping',
  full_name='org.totalgrid.reef.client.service.proto.Simulator.SimulatorMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='org.totalgrid.reef.client.service.proto.Simulator.SimulatorMapping.delay', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='org.totalgrid.reef.client.service.proto.Simulator.SimulatorMapping.measurements', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commands', full_name='org.totalgrid.reef.client.service.proto.Simulator.SimulatorMapping.commands', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=639,
)

_MEASSIM.fields_by_name['type'].enum_type = Measurements__pb2._MEASUREMENT_TYPE
_COMMANDSIM.fields_by_name['response_status'].enum_type = Commands__pb2._COMMANDSTATUS
_SIMULATORMAPPING.fields_by_name['measurements'].message_type = _MEASSIM
_SIMULATORMAPPING.fields_by_name['commands'].message_type = _COMMANDSIM
DESCRIPTOR.message_types_by_name['MeasSim'] = _MEASSIM
DESCRIPTOR.message_types_by_name['CommandSim'] = _COMMANDSIM
DESCRIPTOR.message_types_by_name['SimulatorMapping'] = _SIMULATORMAPPING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeasSim = _reflection.GeneratedProtocolMessageType('MeasSim', (_message.Message,), {
  'DESCRIPTOR' : _MEASSIM,
  '__module__' : 'SimulatorMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Simulator.MeasSim)
  })
_sym_db.RegisterMessage(MeasSim)

CommandSim = _reflection.GeneratedProtocolMessageType('CommandSim', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDSIM,
  '__module__' : 'SimulatorMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Simulator.CommandSim)
  })
_sym_db.RegisterMessage(CommandSim)

SimulatorMapping = _reflection.GeneratedProtocolMessageType('SimulatorMapping', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATORMAPPING,
  '__module__' : 'SimulatorMapping_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Simulator.SimulatorMapping)
  })
_sym_db.RegisterMessage(SimulatorMapping)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
