# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Utils.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Utils.proto',
  package='org.totalgrid.reef.client.service.proto.Utils',
  syntax='proto2',
  serialized_options=b'\n\'org.totalgrid.reef.client.service.protoB\005Utils',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bUtils.proto\x12-org.totalgrid.reef.client.service.proto.Utils\"\xa8\x02\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x02(\t\x12L\n\x05vtype\x18\x02 \x02(\x0e\x32=.org.totalgrid.reef.client.service.proto.Utils.Attribute.Type\x12\x13\n\x0bvdescriptor\x18\x03 \x01(\t\x12\x14\n\x0cvalue_string\x18\n \x01(\t\x12\x14\n\x0cvalue_sint64\x18\x0b \x01(\x12\x12\x14\n\x0cvalue_double\x18\x0c \x01(\x01\x12\x12\n\nvalue_bool\x18\r \x01(\x08\x12\x13\n\x0bvalue_bytes\x18\x0e \x01(\x0c\"?\n\x04Type\x12\n\n\x06STRING\x10\x01\x12\n\n\x06SINT64\x10\x03\x12\n\n\x06\x44OUBLE\x10\x07\x12\x08\n\x04\x42OOL\x10\x08\x12\t\n\x05\x42YTES\x10\t\"\\\n\rAttributeList\x12K\n\tattribute\x18\x01 \x03(\x0b\x32\x38.org.totalgrid.reef.client.service.proto.Utils.AttributeB0\n\'org.totalgrid.reef.client.service.protoB\x05Utils'
)



_ATTRIBUTE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SINT64', index=1, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=3, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=4, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=296,
  serialized_end=359,
)
_sym_db.RegisterEnumDescriptor(_ATTRIBUTE_TYPE)


_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vtype', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.vtype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vdescriptor', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.vdescriptor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.value_string', index=3,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_sint64', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.value_sint64', index=4,
      number=11, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_double', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.value_double', index=5,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_bool', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.value_bool', index=6,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_bytes', full_name='org.totalgrid.reef.client.service.proto.Utils.Attribute.value_bytes', index=7,
      number=14, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ATTRIBUTE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=359,
)


_ATTRIBUTELIST = _descriptor.Descriptor(
  name='AttributeList',
  full_name='org.totalgrid.reef.client.service.proto.Utils.AttributeList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute', full_name='org.totalgrid.reef.client.service.proto.Utils.AttributeList.attribute', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=453,
)

_ATTRIBUTE.fields_by_name['vtype'].enum_type = _ATTRIBUTE_TYPE
_ATTRIBUTE_TYPE.containing_type = _ATTRIBUTE
_ATTRIBUTELIST.fields_by_name['attribute'].message_type = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['AttributeList'] = _ATTRIBUTELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTE,
  '__module__' : 'Utils_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Utils.Attribute)
  })
_sym_db.RegisterMessage(Attribute)

AttributeList = _reflection.GeneratedProtocolMessageType('AttributeList', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTELIST,
  '__module__' : 'Utils_pb2'
  # @@protoc_insertion_point(class_scope:org.totalgrid.reef.client.service.proto.Utils.AttributeList)
  })
_sym_db.RegisterMessage(AttributeList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
